name: Microservices CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    # Setup Python for AI Service
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install AI Service Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r services/ai-service/requirements.txt
        
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 services/ai-service --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 services/ai-service --count --exit-zero --max-complexity=10 --statistics

    # Setup .NET for API Gateway
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Build API Gateway
      run: dotnet build services/api-gateway/api-gateway.csproj --configuration Release

    # Build Docker Images
    - name: Build Docker Images
      run: |
        docker build -t ai-service:latest ./services/ai-service
        docker build -t api-gateway:latest ./services/api-gateway
        docker build -t frontend-service:latest ./services/frontend-service

    # Scan for vulnerabilities (optional but recommended)
    #- name: Docker Scout
    #  uses: docker/scout-action@v1
    #  with:
    #    command: quickview,cves
    #    image: ai-service:latest
